project:
  type: website

website:
  title: "pr-health-heatstress"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://github.com/usf-imars/pr-health-heatstress
        text: Source Code on GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false

jupyter: python3  # use system python


